# DO NOT EDIT THIS FILE, IT IS USED ONLY IN TESTS
# Copyright (C) 2024-2025, Sylwester Kominek
# This file is part of SpectrumAnalyzer program licensed under GPLv2 or later,
# see file LICENSE in this source tree.

import math

def initialize(dataLength, samplingRate):
    global numberOfSamples
    global fs

    numberOfSamples = dataLength
    fs = samplingRate

    return True

def getData():

    signalFrequency = 1000
    samplingPeriod = 1.0/fs
    fullScaleAmplitude = 32767

    result = tuple()

    for sampleNumber in range(numberOfSamples):

        y=fullScaleAmplitude*math.sin(2*math.pi*sampleNumber*signalFrequency*samplingPeriod)
        result += (y,)

    return result
