# DO NOT EDIT THIS FILE, IT IS USED ONLY IN TESTS
# Copyright (C) 2024-2025, Sylwester Kominek
# This file is part of SpectrumAnalyzer program licensed under GPLv2 or later,
# see file LICENSE in this source tree.

def getHorizontalSize():
    return 1
    
def getVerticalSize():
    return 2
    
def getNumberOfSamples():
    return 3
    
def getSamplingRate():
    return 4

def getDesiredFrameRate():
    return 5

def getGapWidthInRelationToRectangleWidth():
    return 5.1
    
def getNumberOfSignalsForAveraging():
    return 6

def getNumberOfSignalsForMaxHold():
    return 7
    
def getMaxQueueSize():
    return 8

def getAlphaFactorForSmoothing():
    return 8.1

def getFrequencies():
    return (1,2,3)  

def getSignalWindow():
    return (4,5,6)

def getScalingFactor():
    return 9
    
def getOffsetFactor():
    return 10
    
def getDynamicMaxHoldVisibilityState():
    return True

def getDynamicMaxHoldRectangleHeightInPercentOfScreenSize():
    return 10.1

def getDynamicMaxHoldSpeedOfFalling():
    return 11

def getDynamicMaxHoldAccelerationStateOfFalling():
    return True

def getColorsOfRectangle(vertex):
    match vertex:
        case 0:
            return (1.1, 1.2, 1.3)
        case 1:
            return (2.1, 2.2, 2.3)
        case 2:
            return (3.1, 3.2, 3.3)
        case 3:
            return (4.1, 4.2, 4.3)
 
def getColorsOfDynamicMaxHoldRectangle(vertex):
    match vertex:
        case 0:
            return (1.1, 2.1, 3.1)
        case 1:
            return (1.2, 2.2, 3.2)
        case 2:
            return (1.3, 2.3, 3.3)
        case 3:
            return (1.4, 2.4, 3.4)  
    
def getAdvancedColorSettings():
    return "test"
